name: Core CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 13
      uses: actions/setup-node@master
      with:
        node-version: '13'
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test

  pack:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12
      uses: actions/setup-node@master
      with:
        node-version: '12'
    - name: npm install
      run: npm install
    - name: npm pack
      run: npm run pack
    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: dist/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
