name: Core CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 16
      uses: actions/setup-node@master
      with:
        node-version: '16'
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test

  pack-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 16
      uses: actions/setup-node@master
      with:
        node-version: '16'
    - name: npm install
      run: npm install
    - name: npm pack
      run: npm run pack

  pack:
    needs: pack-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 16
      uses: actions/setup-node@master
      with:
        node-version: '16'
    - name: npm install
      run: npm install
    - name: npm pack
      run: npm run pack
    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: dist/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: simon300000/ddathome-nodejs:latest
